// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWDgYDn7lDSlA4MP67BGmSZJb7CwIX_t8',
    appId: '1:746122598698:web:3e660fc979d36653f42653',
    messagingSenderId: '746122598698',
    projectId: 'autisticchildrenapp-b82bb',
    authDomain: 'autisticchildrenapp-b82bb.firebaseapp.com',
    storageBucket: 'autisticchildrenapp-b82bb.firebasestorage.app',
    measurementId: 'G-5SCMV5VCSX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAktaOtBxO7dVF0sXP-Wf70TiD5GjKm-hs',
    appId: '1:746122598698:ios:8b2f64b272553b54f42653',
    messagingSenderId: '746122598698',
    projectId: 'autisticchildrenapp-b82bb',
    storageBucket: 'autisticchildrenapp-b82bb.firebasestorage.app',
    iosBundleId: 'com.example.autisticchildren',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWDgYDn7lDSlA4MP67BGmSZJb7CwIX_t8',
    appId: '1:746122598698:web:ad2cc917bff1b016f42653',
    messagingSenderId: '746122598698',
    projectId: 'autisticchildrenapp-b82bb',
    authDomain: 'autisticchildrenapp-b82bb.firebaseapp.com',
    storageBucket: 'autisticchildrenapp-b82bb.firebasestorage.app',
    measurementId: 'G-WM5QH3J5RV',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAktaOtBxO7dVF0sXP-Wf70TiD5GjKm-hs',
    appId: '1:746122598698:ios:8b2f64b272553b54f42653',
    messagingSenderId: '746122598698',
    projectId: 'autisticchildrenapp-b82bb',
    storageBucket: 'autisticchildrenapp-b82bb.firebasestorage.app',
    iosBundleId: 'com.example.autisticchildren',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL87-emCGw0Qqgj7NBvbydMnZEExD9PHU',
    appId: '1:746122598698:android:10ee2d93d8487465f42653',
    messagingSenderId: '746122598698',
    projectId: 'autisticchildrenapp-b82bb',
    storageBucket: 'autisticchildrenapp-b82bb.firebasestorage.app',
  );

}