# Uncomment this line to define a global platform for your project
platform :ios, '15.5'

use_frameworks!
use_modular_headers!

# This line loads the Flutter setup
flutter_application_path = File.expand_path('..', __dir__)
eval(File.read(File.join(flutter_application_path, 'Flutter', 'podhelper.rb')), binding)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # This function installs all Flutter plugin dependencies automatically
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

# ✅ Fix for missing modules like audioplayers_darwin
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
